runtime: python37

env_variables:
  MYSQL_UNIX_SOCKET: "/cloudsql/guideme-capstoneproject:asia-southeast2:guideme-bangkitcapstone"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "guideme1"
  MYSQL_DB: "guideme"
  MYSQL_CURSORCLASS: "DictCursor"
  MYSQL_HOST: "10.11.208.3"

vpc_access_connector:
  name: "projects/guideme-capstoneproject/locations/asia-southeast2/connectors/connect-to-sql"
